### ISSUE TITLE
LaplacesDemon bug in the argument: Algorithm

### ISSUE THREAD

**Issue by SandaD** [ecbrown/LaplacesDemon#5]
Hello,

while running the `LaplacesDemon` with a mistake in the name of the algorithm, the code takes as a default the MWG algorithm without a warning that the specified algorithm doesnt exist. I wanted to run the AIES algorithm but made a mistake and wrote AIEC because that was how it was called in the function description and I was very surprised with the result. It took me a day to realise where was the bug. It would be nice if you could fix it.

Thanks, 

``` R
Fit = LaplacesDemon(Model, Data=MyData, init,
                      Covar=NULL, Iterations=iter, Status=5000, Thinning=1,
                      Algorithm="blabla non existing algorithm", Specs=NULL)
```

**Comment by ecbrown** [comment]
Would you please try #feature/issue-5-laplaces-demon-bug-in-the-argument-algorithm and see if it has the desired behavior?  I changed from default algorithm to stop with error.

**Comment by SandaD** [comment]
Yes, it works perfectly now!
Thanks for such a quick responce.
